timezone: Australia/Melbourne
permalink: /:title

author: Gavin Douch
author_url: https://gavindou.ch

remote_theme: Coedice/cafe-theme

plugins:
  - jekyll-sitemap

sass:
  style: compressed

color_profiles:
  - name: light
    foreground_color: black
    background_color: "#eeeeee"
    transparent_nav_bar_text_color: "#eeeeee"
  - name: dark
    foreground_color: white
    background_color: "#111111"
    transparent_nav_bar_text_color: white
  - name: pink
    foreground_color: black
    background_color: "#e2dbdd"
    transparent_nav_bar_text_color: "#e2dbdd"

font_profiles:
  - name: futuristic
    font_url: https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@500&display=swap
    title_font: '"Red Hat Display", "Century Gothic", Futura, "Avenir Next", Avenir, "Helvetica Neue", Helvetica, Arial, sans-serif'
    body_font: '"Avenir Next", Avenir, "Helvetica Neue", Helvetica, Arial, sans-serif'
  - name: rustic
    font_url: https://fonts.googleapis.com/css2?family=Condiment&display=swap
    title_font: 'Condiment, "Brush Script MT", cursive'
    body_font: '"Helvetica Neue", Helvetica, Arial, sans-serif'
  - name: cursive
    font_url: https://fonts.googleapis.com/css2?family=Cookie&display=swap
    title_font: 'Cookie, "Brush Script MT", cursive'
    body_font: '"Helvetica Neue", Helvetica, Arial, sans-serif'
  - name: formal
    title_font: 'Georgia, "Times New Roman", serif'
    body_font: '"Helvetica Neue", Helvetica, Arial, serif'